# Public client inventory. REMOTE_OPERATIONS mirrors remote_ops.dispatch;
# list_targets, db_save, and python_exec use public Nexus APIs directly.
REMOTE_OPERATIONS = (
    "database_info",
    "segment_list",
    "function_list",
    "function_show",
    "function_frame",
    "function_stackvars",
    "function_callers",
    "function_callees",
    "disasm",
    "disasm_range",
    "decompile",
    "ctree",
    "search_bytes",
    "xrefs",
    "strings",
    "imports",
    "bookmark_get",
    "bookmark_add",
    "bookmark_set",
    "bookmark_delete",
    "comment_get",
    "comment_set",
    "comment_delete",
    "name_set",
    "local_list",
    "local_rename",
    "local_retype",
    "local_update",
    "local_apply_plan",
    "proto_get",
    "proto_check",
    "proto_set",
    "type_list",
    "type_show",
    "type_deps",
    "type_declare",
    "type_declare_check",
    "class_list",
    "class_candidates",
    "class_show",
    "class_hierarchy",
    "class_fields",
    "class_vtable",
    "struct_list",
    "struct_show",
    "struct_field_set",
    "struct_field_rename",
    "struct_field_delete",
    "enum_list",
    "enum_show",
    "enum_member_set",
    "enum_member_rename",
    "enum_member_delete",
    "reanalyze",
)

MUTATING_OPERATIONS = frozenset(
    {
        "bookmark_add",
        "bookmark_set",
        "bookmark_delete",
        "comment_set",
        "comment_delete",
        "name_set",
        "local_rename",
        "local_retype",
        "local_update",
        "local_apply_plan",
        "proto_set",
        "type_declare",
        "struct_field_set",
        "struct_field_rename",
        "struct_field_delete",
        "enum_member_set",
        "enum_member_rename",
        "enum_member_delete",
        "reanalyze",
    }
)

SUPPORTED_OPERATIONS = (
    "list_targets",
    *REMOTE_OPERATIONS,
    "db_save",
    "python_exec",
)


__all__ = ["MUTATING_OPERATIONS", "REMOTE_OPERATIONS", "SUPPORTED_OPERATIONS"]
